### PR TITLE
Add GOOGLE_ABUSE_EXEMPTION cookie

### PR DESCRIPTION
**Pull request by ArshansGithub**
added feature for GOOGLE_ABUSE_EXEMPTION cookie which bypasses the captcha presented by google when passed into search query (optional feature)

### CODE REVIEW

**Comment by opsdisk** [comment]
Hi @ArshansGithub - thanks for submitting the PR.  The `GOOGLE_ABUSE_EXEMPTION` header is interesting...I haven't run into that before.  Can you provide some more background on how they are collected/scraped?  Are they part of a paid Google API offering?

**Comment by ArshansGithub** [comment]
Hey @opsdisk 
Whenever google forces a captcha (to prove you're not a robot) when you solve the captcha it places the `GOOGLE_ABUSE_EXEMPTION` cookie into the browser to be used in further google searches. By harvesting this cookie we can place it in the scraper and further minimize rate limits, etc. No this isn't part of a Google API offering.

**Comment by opsdisk** [comment]
Appreciate the background @ArshansGithub - give me a few days to review the PR.

**Comment by ArshansGithub** [comment]
Any updates?

**Comment by ArshansGithub** [comment]
Any updates?

**Comment by opsdisk** [comment]
Apologies it took longer to get this one.  Appreciate the PR @ArshansGithub!

**Comment by ArshansGithub** [comment]
Awesome stuff, thanks for the approval.

**Pull request merged**
